[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "marimo-pytorch-quantization"
platforms = [{ name = "default", platform = "linux-64", cuda = "12.8" }, { name = "cicd", platform = "linux-64" }]
version = "0.1.0"

[tasks]
start = "CUBLAS_WORKSPACE_CONFIG=:4096:8 marimo edit --headless --port 3000"
lint = "CUBLAS_WORKSPACE_CONFIG=:4096:8 marimo check --ignore-scripts ."
lint-fix = "CUBLAS_WORKSPACE_CONFIG=:4096:8 marimo check --ignore-scripts --fix ."

[tasks.execute]
cmd = "marimo export session {{ notebook_filename }}"

  [[tasks.execute.args]]
  arg = "notebook_filename"

[dependencies]
marimo = ">=0.23.14,<0.24"
python = ">=3.13,<3.14"
numpy = ">=2.0.0,<3"
nbformat = ">=5.10.4,<6"
ruff = ">=0.15.5,<0.16"
nbconvert = ">=7.17.1,<8"
python-lsp-server = ">=1.14.0,<2"
python-lsp-ruff = ">=2.3.0,<3"
scikit-learn = ">=1.9.0,<2"

[target.default.dependencies]
pytorch-gpu = ">=2.9, <2.10"
torchvision = "*"

[target.cicd.dependencies]
pytorch-cpu = ">=2.9, <2.10"
torchvision = "*"

[pypi-dependencies]
mcp-pypi = ">=3.0.0, <4"
playwright = ">=1.61.0, <2"
